"""Appendix A cascade keyword dictionary (translation_key -> RU+UZ terms)."""

from __future__ import annotations

CASCADE_KEYWORDS: dict[str, list[str]] = {
    "food": ["еда", "ovqat"],
    "groceries": ["продукты", "магазин", "супермаркет", "oziq-ovqat", "market", "do'kon", "dokon", "bozorlik", "bozorli", "bozor" , "bozorga", "ro'zg'or", "rozgor", "magazin", "korzinka", "magazin"],
    "cafes_restaurants": ["кафе", "ресторан", "кофе", "обед", "завтрок", "ужин", "kafe", "restoran", "taomxona" , "obet", "obed", "milliy taom", "ujn", "zavtrok", "lavash", "fasfud", "somsa", "osh"],
    "delivery": ["доставка", "яндекс еда", "uzum tezkor", "yetkazib berish", "dostavka"],
    "transport": ["транспорт", "автобус", "метро", "марштрутка", "дамас", "метро", "transport", "avtobus", "metro"],
    "taxi": ["такси", "яндекс такси", "болт", "taksi", "taxi"],
    "fuel": ["бензин", "заправка", "топливо", "газ (авто)", "газ метан", "метан газ", "метан", "газ пропан", "пропан газ", "пропан", "benzin", "yoqilg'i"],
    "public_transport": ["автобус", "метро", "маршрутка", "проезд", "avtobus", "metro"],
    "car_maintenance": ["сто", "автосервис", "шиномонтаж", "мойка", "avto servis", "moyka", "moshina arenda"],
    "home": ["дом", "uy", "hovli", "xovli", "dacha", "дача", "дачу"],
    "rent": ["аренда", "съём квартиры", "ijara", "kvartira arenda"],
    "utilities": ["коммуналка", "свет", "вода", "электричество", "за газ", "kommunal", "komunal", "svet", "gaz", "svet", "elektr", "elektrga"],
    "telecom_internet": ["интернет", "связь", "симкарта", "билайн", "юсел", "узтелеком", "вайфай", "вай-фай", "internet", "aloqa", "telefon", "tarifga", "tarif", "wifi", "wi-fi", "uztelekom", "beeline", "bilayn", "yusel", "ucel"],
    "repairs_furnishing": ["ремонт", "мебель", "стройматериалы", "стройматериалы", "stroymaterial", "remont", "rezetka", "vklyuchatel", "ta'mir", "mebel"],
    "children": ["дети", "bolalar"],
    "kindergarten_school": ["садик", "школа", "детский сад", "bog'cha", "bogcha", "maytab", "inst", "univer", "maktab"],
    "clubs_tutoring": ["кружок", "репетитор", "to'garak", "repetitor"],
    "kids_goods": ["игрушки", "детская одежда", "подгузники", "bolalar buyumlari"],
    "health": ["здоровье", "salomatlik", "sogliq", "sog'liq"],
    "pharmacy": ["лекарства", "аптека", "таблетки", "dori", "dori-darmon", "apteka"],
    "doctors_clinics": ["врач", "клиника", "больница", "анализы", "shifokor", "doxtr", "lorga", "lo'rga", "klinika"],
    "dentistry": ["стоматолог", "зубы", "дантист", "stomatolog", "tish"],
    "events_celebrations": ["мероприятие", "днюха", "день раждение", "корпоратив", "korporativ", "tadbir"],
    "toi_celebrations": ["той", "маърака", "свадьба", "юбилей", "to'y", "toy", "navkar", "marosim"],
    "event_gifts": ["подарок на той", "цветы", "sovg'a", "podarka",],
    "shopping_leisure": ["покупки", "xarid"],
    "clothing": ["одежда", "обувь", "кроссовки", "kiyim", "oyo kiyim", "krasovka", "krasopka", "poyabzal"],
    "entertainment": ["кино", "боулинг", "развлечения", "kino", "ko'ngilochar", "кайфовал", "kaypga",],
    "subscriptions": ["подписка", "netflix", "spotify", "obuna", "netkaga", "cs2", "КС2", "комп", "dota", "dota 2",],
    "beauty_care": ["салон красоты", "парикмахерская", "косметика", "сартарош", "go'zallik saloni", "satarosh"],
    "salary": ["зарплата", "зп", "аванс", "оклад", "maosh", "ish haqi", "oylik", "oyli"],
    "side_job": ["подработка", "фриланс", "шабашка", "qo'shimcha ish", "leviy ish", "leviy"],
    "gifts": ["подарили", "подарок получил", "sovg'a oldim", "podarka", "oyincho", ],
    "family_transfers": [
        "перевод от родителей",
        "от родных",
        "от мамы",
        "от папы",
        "qarindoshdan pul",
    ],
}
