"""Appendix A cascade keyword dictionary (translation_key -> RU+UZ terms)."""

from __future__ import annotations

CASCADE_KEYWORDS: dict[str, list[str]] = {
    "food": ["еда", "ovqat"],
    "groceries": ["продукты", "магазин", "супермаркет", "oziq-ovqat", "market", "do'kon"],
    "cafes_restaurants": ["кафе", "ресторан", "кофе", "обед", "kafe", "restoran", "taomxona"],
    "delivery": ["доставка", "яндекс еда", "uzum tezkor", "yetkazib berish"],
    "transport": ["транспорт", "transport"],
    "taxi": ["такси", "яндекс такси", "болт", "taksi"],
    "fuel": ["бензин", "заправка", "топливо", "газ (авто)", "benzin", "yoqilg'i"],
    "public_transport": ["автобус", "метро", "маршрутка", "проезд", "avtobus", "metro"],
    "car_maintenance": ["сто", "автосервис", "шиномонтаж", "мойка", "avto servis", "moyka"],
    "home": ["дом", "uy"],
    "rent": ["аренда", "съём квартиры", "ijara"],
    "utilities": ["коммуналка", "свет", "вода", "электричество", "kommunal", "svet", "suv"],
    "telecom_internet": ["интернет", "связь", "симкарта", "internet", "aloqa"],
    "repairs_furnishing": ["ремонт", "мебель", "стройматериалы", "ta'mir", "mebel"],
    "children": ["дети", "bolalar"],
    "kindergarten_school": ["садик", "школа", "детский сад", "bog'cha", "maktab"],
    "clubs_tutoring": ["кружок", "репетитор", "to'garak", "repetitor"],
    "kids_goods": ["игрушки", "детская одежда", "подгузники", "bolalar buyumlari"],
    "health": ["здоровье", "salomatlik"],
    "pharmacy": ["лекарства", "аптека", "таблетки", "dori", "apteka"],
    "doctors_clinics": ["врач", "клиника", "больница", "анализы", "shifokor", "klinika"],
    "dentistry": ["стоматолог", "зубы", "дантист", "stomatolog", "tish"],
    "events_celebrations": ["той", "мероприятие", "to'y", "tadbir"],
    "toi_celebrations": ["той", "маърака", "свадьба", "юбилей", "to'y", "marosim"],
    "event_gifts": ["подарок на той", "цветы", "sovg'a"],
    "shopping_leisure": ["покупки", "xarid"],
    "clothing": ["одежда", "обувь", "кроссовки", "kiyim", "poyabzal"],
    "entertainment": ["кино", "боулинг", "развлечения", "kino", "ko'ngilochar"],
    "subscriptions": ["подписка", "netflix", "spotify", "obuna"],
    "beauty_care": ["салон красоты", "парикмахерская", "косметика", "go'zallik saloni"],
    "salary": ["зарплата", "зп", "аванс", "оклад", "maosh", "ish haqi"],
    "side_job": ["подработка", "фриланс", "шабашка", "qo'shimcha ish"],
    "gifts": ["подарили", "подарок получил", "sovg'a oldim"],
    "family_transfers": [
        "перевод от родителей",
        "от родных",
        "от мамы",
        "от папы",
        "qarindoshdan pul",
    ],
}
